
[greenclip]
  blacklisted_applications = ["Qt Selection Owner for keepassxc"]
  enable_image_support = true
  history_file = "/home/$USER/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 500
  max_selection_size_bytes = 0
  static_history = ["~/.config/greenclip.toml"]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
